name: Build

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Configure Git User Details
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace

      - name: Build Jar
        run: ./gradlew shadowJar createPaperclipJar --stacktrace

      - name: Upload MultiPaper
        uses: actions/upload-artifact@v7
        with:
          name: multipaper
          path: multipaper-server/build/libs/multipaper-paperclip-*.jar

      - name: Upload MultiPaper Master
        uses: actions/upload-artifact@v7
        with:
          name: multipaper-master
          path: multipaper-master/build/libs/multipaper-master-*.jar
